version: '2.3'
services:
  CARPentry:
    runtime: nvidia
    build:
      context: ./
    image: carp_container
    container_name: seno_carp
    ports:
      - "3613:8888"
    volumes:
      - ./:/notebooks
      - /mnt:/mnt