version: '2.3'
services:
  CARPentry:
    build:
      context: ./
    image: hbbbhy/carp:latest
    container_name: seno_carp
    ports:
      - "10023:8888"
    volumes:
      - ./:/notebooks
      - /data:/data