version: '2.3'
services:
  CARPentry:
    build:
      context: ./
    image: carp_container:latest
    container_name: seno_carp
    ports:
      - "3612:8888"
    volumes:
      - ./:/notebooks
      - /mnt:/mnt